export const MOCK_PRODUCTS = [
    {
        id: "mock-1",
        name: "Aether Gen-1",
        description: "The ultimate wearable for the modern pioneer. Seamlessly blending style and cutting-edge technology.",
        price: 129.99,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop",
        category: { id: "cat-1", name: "Wearables" },
        isHeroHighlight: true,
        sidebarSide: null,
        specifications: JSON.stringify(["Titanium Build", "12h Battery", "OLED Display", "Water Resistant"]),
    },
    {
        id: "mock-2",
        name: "Nexus Audio",
        description: "Experience sound like never before with high-fidelity acoustics and active noise cancellation.",
        price: 199.50,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
        category: { id: "cat-2", name: "Audio" },
        isHeroHighlight: false,
        sidebarSide: "LEFT",
        specifications: JSON.stringify(["Noise Cancellation", "Spatial Audio", "Bluetooth 5.3", "Leather Pads"]),
    },
    {
        id: "mock-3",
        name: "Zenith Lens",
        description: "Capture the world in stunning detail with our advanced optical technology.",
        price: 450.00,
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1000&auto=format&fit=crop",
        category: { id: "cat-3", name: "Photography" },
        isHeroHighlight: false,
        sidebarSide: "RIGHT",
        specifications: JSON.stringify(["F1.8 Aperture", "Glass Optics", "Auto Focus", "Compact Design"]),
    },
    {
        id: "mock-4",
        name: "Titan Blade",
        description: "Precision engineered for the perfect cut. Minimalist design meets maximum performance.",
        price: 85.00,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
        category: { id: "cat-4", name: "Essentials" },
        isHeroHighlight: false,
        sidebarSide: null,
        specifications: JSON.stringify(["Carbon Steel", "G10 Handle", "Lifetime Warranty"]),
    },
    {
        id: "mock-5",
        name: "Onyx Flask",
        description: "Keep your drinks at the perfect temperature for hours. Designed for explorers.",
        price: 45.00,
        image: "https://images.unsplash.com/photo-1602143393494-1428a30b593a?q=80&w=1000&auto=format&fit=crop",
        category: { id: "cat-4", name: "Essentials" },
        isHeroHighlight: false,
        sidebarSide: null,
        specifications: JSON.stringify(["Vacuum Isolated", "500ml Capacity", "BPA Free"]),
    }
];
